# Generated by Django 4.0.10 on 2023-06-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='telegram_id',
            field=models.CharField(default='', max_length=100, verbose_name='Telegram ID'),
        ),
    ]
