# Generated by Django 4.0.10 on 2023-08-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_first_name_account_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='school_class',
            field=models.CharField(default='', max_length=100, verbose_name='Класс'),
        ),
    ]
