# Generated by Django 4.2.2 on 2023-08-04 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 4, 11, 17, 56, 69053), verbose_name='Дата конспекта'),
        ),
    ]
