# Generated by Django 4.2.2 on 2023-08-05 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 6, 0, 19, 17, 184727), verbose_name='Дата конспекта'),
        ),
    ]
