# Generated by Django 4.0.10 on 2023-06-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('name', models.CharField(max_length=200, verbose_name='Предмет')),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
