# Generated by Django 4.0.10 on 2023-06-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='deadline',
            field=models.DateField(auto_now=True, verbose_name='Срок сдачи'),
        ),
        migrations.AddField(
            model_name='homework',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Сделано?'),
        ),
    ]
