# Generated by Django 4.0.10 on 2023-06-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0002_homework_deadline_homework_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='deadline',
            field=models.DateField(blank=True, verbose_name='Срок сдачи'),
        ),
    ]
